### ISSUE TITLE
Uncaught TypeError: $(...).zIndex is not a function

### ISSUE THREAD

**Issue by rinkudas** [zorab47/jquery-monthpicker-rails#1]
Getting error in production as:

 jquery.ui.monthpicker-370bc3b….js:1 Uncaught TypeError: $(...).zIndex is not a function
    at HTMLInputElement._showMonthpicker (jquery.ui.monthpicker-370bc3b….js:1)
    at HTMLInputElement.dispatch (active_admin-eac3186….js:2)
    at HTMLInputElement.g.handle (active_admin-eac3186….js:2)

Though it is working in local.

**Comment by GhennadiiMir** [comment]
It depends on version of jQuery which do you use. Newest versions do not support .zIndex function

**Comment by rinkudas** [comment]
So What is the work around?

**Comment by zorab47** [comment]
Thanks for reporting. Perhaps there is a way to conditionally exclude zIndex for newer version of jQuery?

**Comment by pablosalgadom** [comment]
I solved the problem changing in this file **jquery.ui.monthpicker.js** this line of code:

`inst.dpDiv.zIndex($(input).zIndex()+1);`

for this one:
`inst.dpDiv.css( "zIndex", $(input).css( "zIndex")+1 );`

Hope it helps :D

**Comment by zorab47** [comment]
Thanks for reporting. It has been resolved in the JS repo and needs to be
updated here to fix the issue.

**Comment by zorab47** [comment]
Released a new version 1.0.1 to rubygems resolving the zIndex issue. See the change log for more details: https://github.com/zorab47/jquery-monthpicker-rails/blob/master/CHANGELOG.md

**Comment by reetak18** [comment]
Received following error with Cake 2.10.9 version when I ran ./Console/cake AclExtras.AclExtras aco_sync though I have DecisionsController in app/Controller.
I could not find a solution for this problem in this thread

Error: Class DecisionsController does not exist
#0 /conundrum/gotd_vX/app/Plugin/AclExtras/Lib/AclExtras.php(235): ReflectionClass->__construct('DecisionsContro...')
#1 /conundrum/gotd_vX/app/Plugin/AclExtras/Lib/AclExtras.php(272): AclExtras->_getCallbacks('DecisionsContro...')
#2 /conundrum/gotd_vX/app/Plugin/AclExtras/Lib/AclExtras.php(167): AclExtras->_checkMethods('DecisionsContro...', 'Decisions', Array, NULL)
#3 /conundrum/gotd_vX/app/Plugin/AclExtras/Lib/AclExtras.php(119): AclExtras->_updateControllers(Array, Array)
#4 /conundrum/gotd_vX/app/Plugin/AclExtras/Lib/AclExtras.php(106): AclExtras->aco_update(Array)
#5 /conundrum/gotd_vX/app/Plugin/AclExtras/Console/Command/AclExtrasShell.php(64): AclExtras->aco_sync(Array)
#6 /conundrum/gotd_vX/lib/Cake/Console/Shell.php(459): AclExtrasShell->aco_sync()
#7 /conundrum/gotd_vX/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('aco_sync', Array)
#8 /conundrum/gotd_vX/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#9 /conundrum/gotd_vX/app/Console/cake.php(47): ShellDispatcher::run(Array)
#10 {main}
